### PR TITLE
Revisioning

### PR DESCRIPTION
**Pull request by JoshuaSlui**
This improves the code for the `pay` command, also minimising it.
I also removed the `try: except` block from the withdraw command, which should have been removed prior to pushing.

### CODE REVIEW

**Review by Soapy7261 — APPROVED** [review]
```
if change.type == "SQL":
    review.soapy = "Approve"
```

**Comment by JoshuaSlui** [comment]
Start learning SQL you lazy ass, smh

**Comment by Soapy7261** [comment]
ratiomeme

**Comment by JoshuaSlui** [comment]
Screenshot_2023-08-10-18-30-58-656-edit_com discord
🤓

**Comment by Soapy7261** [comment]
You added it to tpk in the first place

**Comment by Soapy7261** [comment]
Also you posted gay sex, i posted ratio

**Comment by Soapy7261** [comment]
storm
Need i remind you?

**Pull request merged**
